version: '3.4'

x-environment: &environment
  MONGODB_URI: mongodb://mongodb:27017/
  DATABASE: database
  COLLECTION: writeups

services:
  spider:
    build: ./spider
    image: wsi-spider:latest
    container_name: wsi_spider
    restart: unless-stopped
    environment:
      <<: *environment
      CTFTIME_URL: https://ctftime.org
      USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
      PYTHONWARNINGS: ignore:Unverified HTTPS request
      TIMEOUT: 2
    depends_on:
      - mongodb
  web:
    build: ./web
    image: wsi-web:latest
    container_name: wsi_web
    ports:
      - "80:80"
    restart: unless-stopped
    environment: *environment
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: wsi_mongodb
    restart: unless-stopped
    volumes:
      - .data:/data/db
